name: CI

env:
  RAILS_ENV: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test:
    name: ${{ github.workflow }} redmine-${{ matrix.version }} ${{ matrix.db }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['4.2', '5.0']
        db: ['postgres']

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: redmine:${{ matrix.version }}
      env:
        REDMINE_HOME: /usr/src/redmine
        RAILS_ENV: ${{ env.RAILS_ENV }}

    steps:
    - uses: actions/checkout@v3
    - name: Run plugin tests
      env:
        # use localhost for the host here because we have specified a container for the job.
        # If we were running the job on the VM this would be postgres
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: ${{ env.RAILS_ENV }}
      working-directory: redmine
      run: |
        pwd
        cd /usr/src/redmine/plugins
        ls -la
