name: CI

env:
  RAILS_ENV: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test:
    name: redmine-${{ matrix.version }} ${{ matrix.db }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['5.0.2']
        db: ['postgres']

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: redmine:${{ matrix.version }}
      env:
        REDMINE_HOME: /usr/src/redmine
        RAILS_ENV: ${{ env.RAILS_ENV }}

    steps:
    - name: Log ruby and rails version
      run: |
        ruby -v
        rails -v
