name: CI

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  REDMINE_HOME: /usr/src/redmine
  RAILS_ENV: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test:
    name: redmine-${{ matrix.version }} ${{ matrix.db }}
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ${{ env.REDMINE_HOME }}

    strategy:
      fail-fast: false
      matrix:
        version: ['5.0.2']
        db: ['postgres']

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: redmine:${{ matrix.version }}

    steps:
    - name: Test
      run: |
        PLUGIN_DIR=`pwd`
        PLUGIN_NAME=`basename ${PLUGIN_DIR}`
        echo "PLUGIN_NAME=${PLUGIN_NAME}" >> $GITHUB_ENV
        cd ${REDMINE_HOME}/plugins
        ln -s ${PLUGIN_DIR} ${PLUGIN_NAME}
