name: CI

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  REDMINE_HOME: /usr/src/redmine
  RAILS_ENV: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test:
    name: redmine-${{ matrix.version }} ${{ matrix.db }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.REDMINE_HOME }}

    strategy:
      fail-fast: false
      matrix:
        version: [3.4.13, 4.2.7, 5.0.2]
        db: [postgres]

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: redmine:${{ matrix.version }}
      volumes:
        - ${{ github.workspace }}:/usr/src/redmine/plugins/redmine_redis_notifier

    steps:
    - uses: actions/checkout@v3

    - name: Install essential
      run: apt-get update && apt-get install -y build-essential

    - name: Create database.yml (PostgreSQL)
      run: |
        cat > config/database.yml <<EOF
        test:
          adapter: postgresql
          host: postgres
          port: 5432
          username: <%= ENV["POSTGRES_USER"] %>
          password: <%= ENV["POSTGRES_PASSWORD"] %>
          database: "redmine"
          encoding: "utf8"
        EOF

    - name: Setup environment
      run: |
        bundle install --with test
        bundle exec rake db:drop db:create db:migrate redmine:plugins:migrate

    - name: Run plugin tests
      run: |
        bundle exec rails test plugins/redmine_redis_notifier/test
